[package]
name = "ynab-importer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.41.1", features = ["full"] }
uuid = { version = "1.11.0" }
notify = { version = "6.1.1", features = ["serde"] }
rusqlite = { version = "0.31.0", features = ["bundled"] }
refinery = { version = "0.8.14", features = ["rusqlite"]}

[dependencies.ynab_api]
path = "api-lib"
